@baseUrl = http://localhost:5001

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials:true

{
  "userTo":"6737b089d16c37ad9ff9df0a",
  "postId":"6739000c165b7b605d530b26",
  "comment": "Hope you are good",
  "profilePicture":"https://res.cloudinary.com/dogpykohr/image/upload/v1726904784/66ee79ce63095810f63337e9"
}





###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/67147658752649f86b3c67af
Content-Type: application/json
Accept: application/json
withCredentials:true



###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/67147658752649f86b3c67af/671fd83a6d1c3740f32a365a
Content-Type: application/json
Accept: application/json
withCredentials:true
