@baseUrl = http://localhost:5001

@urlPath = api/v1


###
PUT  {{baseUrl}}/{{urlPath}}/notification/67390154a2d84d4a38fc3959
Content-Type: application/json
Accept: application/json
withCredentials:true




###
DELETE   {{baseUrl}}/{{urlPath}}/notification/67390154a2d84d4a38fc3959
Content-Type: application/json
Accept: application/json
withCredentials:true




###
GET   {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials:true


