@baseUrl = http://localhost:5001

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials:true

{
  "userTo":"67147641752649f86b3c67a8",
  "postId":"67147658752649f86b3c67af",
  "type":"wow",
  "previousReaction":"",
  "postReactions":{"like":0,"love":0,"happy":0,"sad":0,"wow":1,"angry":0},
  "profilePicture":"https://res.cloudinary.com/dogpykohr/image/upload/v1726904784/66ee79ce63095810f63337e9"
}



###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/67147658752649f86b3c67af/wow/{"like":0,"love":0,"happy":0,"sad":0,"wow":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials:true

{}




###
GET {{baseUrl}}/{{urlPath}}/post/reactions/67147658752649f86b3c67af
Content-Type: application/json
Accept: application/json
withCredentials:true

{}




###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Danny/67147658752649f86b3c67af
Content-Type: application/json
Accept: application/json
withCredentials:true

{}


###
GET {{baseUrl}}/{{urlPath}}//post/reactions/username/Danny
Content-Type: application/json
Accept: application/json
withCredentials:true

{}






